View space details
rgollancz/makers-bnb pull request #21
Opened 2016-11-01 16:44 UTC by fbell123

2016-11-01 16:44 UTC, fbell123 commented
@rgollancz @lauraweston please review 🎱

2016-11-01 16:50 UTC, rgollancz commented on app/app.rb
> +    space = Space.all(id: params[:id])
Should only ever retrieve one space, so should be '@space = Space.all(id: params[:id])' and then pass the single space to the erb.

2016-11-01 16:51 UTC, rgollancz commented on app/app.rb
> +    @spaces = space
...so this can be deleted

2016-11-01 16:53 UTC, rgollancz commented on app/models/space.rb
> -  belongs_to :user
We need this for the model - was it removed for testing? If so, we've hard-coded user_id in the controller until we have sessions.

2016-11-01 16:54 UTC, rgollancz commented on app/views/spaces/individual.erb
> +  <% @spaces.each do |space| %>
As per above - doesn't need to be a loop when they'll only be one space.

2016-11-01 16:56 UTC, rgollancz commented on app/views/spaces/spaces.erb
> +        Name: <a href="http://localhost:9292/spaces/<%=space.id%>" ><%= space.name %></a><br>
shouldn't this be a relative route (/spaces/) - otherwise it won't work outside the test/dev environments

2016-11-01 16:57 UTC, rgollancz commented on app/views/spaces/spaces.erb
> +  <a href="http://localhost:9292/spaces/new">Add new Space</a>
same as above - needs to be relative

2016-11-01 16:57 UTC, rgollancz commented on spec/app_spec.rb
> -      expect(last_response).to be_ok
why was this removed?

2016-11-01 16:59 UTC, rgollancz commented on spec/spec_helper.rb
> +DatabaseCleaner.strategy = :truncation
do we need this here and in the RSpec config section?

2016-11-01 17:00 UTC, rgollancz requested changes
See comments 😄

2016-11-02 10:45 UTC, rgollancz commented on app/views/spaces/individual.erb
> +<ul>
we aren't formatting these as a list, so ul and li tags can be removed

2016-11-02 10:47 UTC, rgollancz commented on spec/app_spec.rb
> +      # post '/spaces', name: "One", address: "14 Two Lane", description: "It's a house", price: 130.64
please delete

2016-11-02 10:52 UTC, rgollancz approved these changes
:shipit:

2016-11-02 10:52 UTC, merged